[build]
command = "./build.sh"
functions = "api"
publish = "dist"

[build.environment]
GO_IMPORT_PATH = "github.com/corioder/be.safe/api"
GO111MODULE = "on"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
