[build]
command = "./build.sh"
functions = "api"
publish = "dist"

[build.environment]
GO_IMPORT_PATH = "github.com/corioder/be.safe/api"
GO111MODULE = "on"

[[redirects]]
from = "/api/*"
to = "/.netlify/api/api/:splat"
status = 200


# github.com/carlmjohnson/netlify-function-cache-test
# github.com/carlmjohnson/netlify-go-function-demo
